FROM node:16.11.1-alpine3.13 AS builder
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:16.11.1-alpine3.13
WORKDIR /app
COPY --from=builder /app ./
CMD ["npm", "run", "start:prod"]