export enum ConfigFields {
  SENTRY_DSN = 'SENTRY_DSN',
  NODE_ENV = 'NODE_ENV',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  RUN_MIGRATIONS = 'RUN_MIGRATIONS',
}
